services:
  web:
    build: .
    ports:
      - 8080:8080

  mongodb:
    image: bitnami/mongodb
    ports:
      - 27017
    volumes:
      - mongodb-data:/bitnami/mongodb

volumes:
  mongodb-data:
